<a href="https://colab.research.google.com/github/nmquintero/MLandDS/blob/main/Data%20Preprocessing/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Sprint 10: Data Preprocessing

1. **Data Cleaning Techniques and Handling Missing Values**
   - **Introduction to Data Cleaning:**
     - The importance of data cleaning in the data preprocessing pipeline.
     - Common data quality issues: duplicates, incorrect data types, outliers, and inconsistencies.
   - **Handling Missing Values:**
     - Understanding types of missing data: MCAR (Missing Completely at Random), MAR (Missing at Random), MNAR (Missing Not at Random).
     - Techniques for handling missing values:
       - **Removing Missing Data:** When and how to drop rows or columns with missing values.
       - **Imputation Methods:**
         - Simple imputation: Mean, median, and mode.
         - Advanced imputation: KNN imputation, multivariate imputation, and regression imputation.
       - **Creating Indicator Variables:** Use of binary flags to indicate the presence of missing data.

2. **Data Scaling and Normalization**
   - **Importance of Data Scaling:**
     - How scaling affects the performance of machine learning algorithms, especially those based on distance or gradient descent.
   - **Scaling Techniques:**
     - **Min-Max Scaling:** Rescaling data to a fixed range, typically 0 to 1.
     - **Z-Score Normalization (Standardization):** Adjusting data to have a mean of 0 and a standard deviation of 1.
     - **Robust Scaling:** Scaling using the median and interquartile range, effective for data with outliers.
   - **When to Use Each Technique:** Practical guidelines for choosing the appropriate scaling method.

3. **Introduction to Feature Engineering**
   - **Definition and Importance:**
     - Transforming raw data into features that better represent the underlying problem to the predictive models.
   - **Techniques in Feature Engineering:**
     - **Creating New Features:** Deriving new features from existing ones (e.g., combining or transforming variables).
     - **Encoding Categorical Variables:** Techniques like one-hot encoding, label encoding, and target encoding.
     - **Interaction Features:** Creating features by combining multiple variables to capture their interaction.
     - **Polynomial Features:** Generating polynomial combinations of features to model non-linear relationships.

### Few words about scikit-learn

We will use **`scikit-learn`**, often abbreviated as `sklearn`, - one of the most popular and powerful open-source libraries in Python for machine learning and data analysis. It provides a comprehensive suite of tools for building, evaluating, and deploying machine learning models, making it an essential tool for data scientists, machine learning engineers, and statisticians.

##### **Key Features of `scikit-learn`:**

1. **Machine Learning Algorithms:**
   - `scikit-learn` includes a wide array of machine learning algorithms for both supervised and unsupervised learning tasks. This includes algorithms for:
     - **Classification:** Logistic Regression, Support Vector Machines (SVM), Random Forests, k-Nearest Neighbors (k-NN), Naive Bayes, etc.
     - **Regression:** Linear Regression, Ridge Regression, Lasso, Decision Trees, etc.
     - **Clustering:** K-Means, Hierarchical Clustering, DBSCAN, etc.
     - **Dimensionality Reduction:** Principal Component Analysis (PCA), t-SNE, etc.
     - **Model Selection and Evaluation:** Tools like Grid Search, Cross-Validation, and metrics such as accuracy, precision, recall, F1-score, and more.

2. **Preprocessing Tools:**
   - `scikit-learn` offers a variety of preprocessing utilities for preparing data before it is fed into a machine learning model. This includes:
     - **Data Scaling and Normalization:** `StandardScaler`, `MinMaxScaler`, `RobustScaler`.
     - **Encoding Categorical Variables:** `OneHotEncoder`, `LabelEncoder`.
     - **Feature Engineering:** Polynomial features, interaction terms, and more.
     - **Imputation:** `SimpleImputer`, `KNNImputer` for handling missing data.
   
3. **Model Validation and Selection:**
   - `scikit-learn` provides powerful tools for model validation and hyperparameter tuning, ensuring that your models generalize well to unseen data.
     - **Cross-Validation:** Techniques like k-fold cross-validation, stratified k-fold, and more.
     - **Grid Search and Random Search:** `GridSearchCV`, `RandomizedSearchCV` to find the best hyperparameters for your models.
   
4. **Pipelines:**
   - Pipelines in `scikit-learn` allow you to streamline the process of creating machine learning workflows by combining multiple steps (e.g., preprocessing, model fitting) into a single, cohesive process.
     - **Example:**
       ```python
       from sklearn.pipeline import Pipeline
       from sklearn.preprocessing import StandardScaler
       from sklearn.linear_model import LogisticRegression

       pipeline = Pipeline([
           ('scaler', StandardScaler()),
           ('classifier', LogisticRegression())
       ])

       pipeline.fit(X_train, y_train)
       ```

5. **Model Evaluation Metrics:**
   - `scikit-learn` includes a rich set of metrics for evaluating model performance, from standard accuracy to more complex metrics like ROC AUC, mean squared error (MSE), and adjusted R².
     - **Example:**
       ```python
       from sklearn.metrics import accuracy_score, confusion_matrix

       y_pred = pipeline.predict(X_test)
       accuracy = accuracy_score(y_test, y_pred)
       cm = confusion_matrix(y_test, y_pred)
       ```

6. **Ease of Use:**
   - `scikit-learn` is designed with simplicity in mind, using consistent and intuitive APIs. It integrates seamlessly with other popular Python libraries such as NumPy, SciPy, and Pandas, allowing for easy data manipulation and visualization.
   
7. **Extensive Documentation and Community Support:**
   - The library is well-documented, with extensive tutorials, examples, and user guides available. It also has a large and active community, making it easy to find help and resources.

##### **Use Cases:**

- **Data Preprocessing:** Preparing raw data for analysis, including handling missing values, scaling, and encoding.
- **Building Predictive Models:** Developing models for tasks such as predicting customer churn, classifying images, or forecasting sales.
- **Feature Engineering:** Enhancing the predictive power of datasets by creating new features or transforming existing ones.
- **Model Evaluation:** Assessing the performance of machine learning models to ensure they generalize well to new data.
- **Hyperparameter Tuning:** Finding the best parameters for machine learning models to optimize their performance.

##1. Data Cleaning Techniques and Handling Missing Values

In the real world, raw data is rarely perfect. It often contains errors, inconsistencies, and missing values. Data cleaning is the process of detecting and correcting these issues to improve the quality of the data, which is crucial for building reliable machine learning models.

###1.1. Common Data Issues
- **Duplicates:** These are repeated entries in the dataset. Duplicate rows can skew your analysis or model, especially if they represent the same event or entity.
- **Incorrect Data Types:** Data that is incorrectly typed (e.g., numbers stored as strings) can lead to errors in analysis and model training.
- **Outliers:** Extreme values that are far removed from the rest of the data. They can distort the results of statistical analyses or machine learning models.

###1.2. Handling Missing Values
Missing data can occur for various reasons, such as data entry errors, equipment malfunctions, or privacy concerns. It's essential to handle missing values carefully, as improper handling can lead to biased results.

**Types of Missing Data:**
- **MCAR (Missing Completely at Random):** The probability of data being missing is independent of the data itself.
- **MAR (Missing at Random):** The probability of missing data is related to other observed data, but not to the missing data itself.
- **MNAR (Missing Not at Random):** The missingness is related to the unobserved data itself.

###1.3. Techniques for Handling Missing Values

- **Removing Missing Data:** Dropping rows or columns with missing values is the simplest approach, but it can lead to loss of valuable information.

In [50]:
#You need this code block only in case using Google Colaboratory
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/Othercomputers/Mi MacBook Air (1)/MASTER IA/Data Preprocessing

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/Othercomputers/Mi MacBook Air (1)/MASTER IA/Data Preprocessing

In [75]:
import pandas as pd

df = pd.read_csv('data.csv')
df_cleaned = df.dropna()  # Drops all rows with any missing values
# Drop rows with any missing values in numerical columns
df = df.dropna(subset=['feature1', 'feature2'])

In [76]:
df.head(4)

,feature1,feature2,feature,height,weight,date,color,target,age,income,x,categorical_column
0,25.5,30.2,10,1.60,55,2024-01-01,red,1,25,30000,2,low
3,45.0,55.3,150,1.90,90,2024-03-10,red,1,55,90000,5,very_high
4,18.7,22.4,200,1.68,60,2024-07-22,blue,1,28,35000,6,low
5,60.2,45.1,10,1.72,68,2024-02-14,green,0,32,48000,7,medium

In [77]:
df_cleaned.head(4)

,feature1,feature2,feature,height,weight,date,color,target,age,income,x,categorical_column
0,25.5,30.2,10,1.60,55,2024-01-01,red,1,25,30000,2,low
3,45.0,55.3,150,1.90,90,2024-03-10,red,1,55,90000,5,very_high
4,18.7,22.4,200,1.68,60,2024-07-22,blue,1,28,35000,6,low
5,60.2,45.1,10,1.72,68,2024-02-14,green,0,32,48000,7,medium

**Imputation Methods:**
  - **Mean Imputation:** Replace missing values with the mean of the column.

In [78]:
# Impute missing values with the mean of the respective column
df['feature1'].fillna(df['feature1'].mean(), inplace=True)
df['feature2'].fillna(df['feature2'].mean(), inplace=True)

/tmp/ipykernel_9249/2010758680.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['feature1'].fillna(df['feature1'].mean(), inplace=True)
/tmp/ipykernel_9249/2010758680.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['feature2'].fillna(df['feature2'].mean(), inplace=True)

In [79]:
df.head(4)

,feature1,feature2,feature,height,weight,date,color,target,age,income,x,categorical_column
0,25.5,30.2,10,1.60,55,2024-01-01,red,1,25,30000,2,low
3,45.0,55.3,150,1.90,90,2024-03-10,red,1,55,90000,5,very_high
4,18.7,22.4,200,1.68,60,2024-07-22,blue,1,28,35000,6,low
5,60.2,45.1,10,1.72,68,2024-02-14,green,0,32,48000,7,medium

  - **Median Imputation:** Useful when the data is skewed.

In [80]:
df['feature1'].fillna(df['feature1'].median(), inplace=True)

/tmp/ipykernel_9249/845216444.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['feature1'].fillna(df['feature1'].median(), inplace=True)

In [81]:
df.head(4)

,feature1,feature2,feature,height,weight,date,color,target,age,income,x,categorical_column
0,25.5,30.2,10,1.60,55,2024-01-01,red,1,25,30000,2,low
3,45.0,55.3,150,1.90,90,2024-03-10,red,1,55,90000,5,very_high
4,18.7,22.4,200,1.68,60,2024-07-22,blue,1,28,35000,6,low
5,60.2,45.1,10,1.72,68,2024-02-14,green,0,32,48000,7,medium

  - **Mode Imputation:** Often used for categorical data.

In [82]:
df['feature1'].fillna(df['feature1'].mode()[0], inplace=True)

/tmp/ipykernel_9249/1991520260.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['feature1'].fillna(df['feature1'].mode()[0], inplace=True)

In [83]:
df.head(4)

,feature1,feature2,feature,height,weight,date,color,target,age,income,x,categorical_column
0,25.5,30.2,10,1.60,55,2024-01-01,red,1,25,30000,2,low
3,45.0,55.3,150,1.90,90,2024-03-10,red,1,55,90000,5,very_high
4,18.7,22.4,200,1.68,60,2024-07-22,blue,1,28,35000,6,low
5,60.2,45.1,10,1.72,68,2024-02-14,green,0,32,48000,7,medium

- **Advanced Imputation:**
  - **K-Nearest Neighbors (KNN) Imputation:** Estimates missing values based on the values of the nearest neighbors.
  - **Multivariate Imputation:** Considers the relationships between features to impute missing values.

**Creating Indicator Variables:**
Another approach is to create a binary indicator variable that flags the presence of missing data.

In [84]:
df['missing_column'] = df['feature1'].isnull().astype(int)

In [85]:
df.head(4)

,feature1,feature2,feature,height,weight,date,color,target,age,income,x,categorical_column,missing_column
0,25.5,30.2,10,1.60,55,2024-01-01,red,1,25,30000,2,low,0
3,45.0,55.3,150,1.90,90,2024-03-10,red,1,55,90000,5,very_high,0
4,18.7,22.4,200,1.68,60,2024-07-22,blue,1,28,35000,6,low,0
5,60.2,45.1,10,1.72,68,2024-02-14,green,0,32,48000,7,medium,0

## 2. Data Scaling and Normalization

In machine learning, data scaling and normalization are crucial preprocessing steps that can significantly affect the performance of your models. These techniques are particularly important for algorithms that rely on distance metrics (e.g., K-Nearest Neighbors, Support Vector Machines) or gradient-based optimization methods (e.g., linear regression, neural networks). Below, we will explore why scaling is important, different scaling techniques, and when to use each technique.

###2.1. Importance of Data Scaling

Data scaling ensures that all features contribute equally to the model's learning process. When features have vastly different ranges, those with larger ranges can dominate the distance calculations or the gradient steps, leading to suboptimal models. For instance:

- **Distance-based Algorithms:** In algorithms like K-Nearest Neighbors (KNN) or Support Vector Machines (SVM), the distance between data points is crucial. If one feature has a much larger range than others, it will disproportionately influence the distance metric, potentially skewing the results.
  
- **Gradient Descent:** Algorithms like linear regression and neural networks use gradient descent to minimize a cost function. If the features are not scaled, the gradient descent algorithm may take longer to converge or may converge to a suboptimal solution due to the uneven steps taken in the parameter space.

###2.2. Scaling Techniques

#### **Min-Max Scaling**

**Min-Max Scaling** (or normalization) rescales the data to a fixed range, usually [0, 1]. This technique is particularly useful when you know that your data follows a distribution with clear upper and lower bounds.

**Formula:**
$$
X' = \frac{X - X_{\text{min}}}{X_{\text{max}} - X_{\text{min}}}
$$
Where:
- $X$ is the original value.
- $X_{\text{min}}$ and $X_{\text{max}}$ are the minimum and maximum values of the feature.

**Example:**

Suppose you have a feature with values ranging from 10 to 200. Applying Min-Max Scaling to this feature will rescale it to a range of [0, 1].

In [86]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

df = pd.read_csv('data.csv')

# Select only numerical columns for scaling
numerical_df = df.select_dtypes(include=['number'])

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(numerical_df)

print(scaled_data)

[[0.18735363 0.20487805 0.         0.         0.07894737 1.
  0.09090909 0.07692308 0.        ]
 [0.34192037        nan 0.21052632 0.5        0.73684211 0.
  0.39393939 0.38461538 0.125     ]
 [       nan        nan 0.47368421 0.73333333 0.52631579 0.
  0.6969697  0.69230769 0.25      ]
 [0.6440281  0.81707317 0.73684211 1.         1.         1.
  1.         1.         0.375     ]
 [0.02810304 0.01463415 1.         0.26666667 0.21052632 1.
  0.18181818 0.15384615 0.5       ]
 [1.         0.56829268 0.         0.4        0.42105263 0.
  0.3030303  0.35384615 0.625     ]
 [0.38173302        nan 0.21052632 0.83333333 0.86842105 0.
  0.54545455 0.56923077 0.75      ]
 [0.55737705 0.41219512 0.47368421 0.6        0.57894737 1.
  0.48484848 0.46153846 0.875     ]
 [0.28337237 0.28292683 0.73684211 0.16666667 0.15789474 0.
  0.24242424 0.24615385 1.        ]
 [0.87822014 0.93414634 1.         0.33333333 0.28947368 1.
  0.60606061 0.66153846 0.        ]
 [0.1147541  0.17317073 0.         0.93333333 0.78947368 0.
  0.15151515 0.10769231 0.125     ]
 [0.4824356  0.50731707 0.21052632 0.66666667 0.68421053 1.
  0.33333333 0.4        0.25      ]
 [       nan        nan 0.73684211 0.06666667 0.         0.
  0.21212121 0.2        0.375     ]
 [0.70960187 0.74390244 1.         0.53333333 0.47368421 1.
  0.66666667 0.72307692 0.5       ]
 [0.07025761 0.07073171 0.         0.8        0.94736842 0.
  0.27272727 0.30769231 0.625     ]
 [0.43793911 0.45609756 0.21052632 0.3        0.26315789 1.
  0.42424242 0.50769231 0.75      ]
 [0.82435597 0.66097561 0.47368421 0.43333333 0.36842105 0.
  0.78787879 0.76923077 0.875     ]
 [0.62295082        nan 0.73684211 0.9        0.71052632 1.
  0.12121212 0.06153846 1.        ]
 [0.2295082  0.26829268 1.         0.2        0.13157895 0.
  0.36363636 0.43076923 0.        ]
 [0.5175644  0.54634146 0.         0.63333333 0.63157895 1.
  0.57575758 0.61538462 0.125     ]
 [0.32552693 0.36341463 0.21052632 0.36666667 0.34210526 0.
  0.51515152 0.52307692 0.25      ]
 [0.71896956 0.78292683 0.47368421 0.76666667 0.84210526 1.
  0.72727273 0.70769231 0.375     ]
 [0.14754098 0.14146341 0.73684211 0.13333333 0.05263158 0.
  0.45454545 0.47692308 0.5       ]
 [0.93208431 1.         1.         0.56666667 0.55263158 1.
  0.63636364 0.67692308 0.625     ]
 [0.39812646 0.42195122 0.         0.86666667 0.89473684 0.
  0.06060606 0.03076923 0.75      ]
 [0.59484778 0.62439024 0.21052632 0.1        0.10526316 1.
  0.39393939 0.44615385 0.875     ]
 [0.03981265 0.04146341 0.47368421 0.7        0.76315789 0.
  0.75757576 0.75384615 1.        ]
 [0.77517564 0.82926829 0.73684211 0.46666667 0.44736842 1.
  0.84848485 0.81538462 0.        ]
 [0.46604215 0.47560976 1.         0.23333333 0.23684211 0.
  0.         0.         0.125     ]
 [0.21779859 0.22439024 0.         0.96666667 0.92105263 1.
  0.81818182 0.78461538 0.25      ]
 [0.66042155 0.69268293 0.21052632 0.03333333 0.02631579 0.
  0.33333333 0.36923077 0.375     ]
 [       nan        nan 0.47368421 0.6        0.60526316 1.
  0.48484848 0.55384615 0.5       ]
 [0.29742389 0.33658537 0.73684211 0.33333333 0.31578947 0.
  0.21212121 0.23076923 0.625     ]
 [0.84074941 0.88536585 1.         0.83333333 0.81578947 1.
  0.6969697  0.69230769 0.75      ]
 [0.09836066 0.1097561  0.         0.26666667 0.18421053 0.
  0.27272727 0.32307692 0.875     ]
 [0.53395785 0.58536585 0.21052632 0.53333333 0.5        1.
  0.45454545 0.49230769 1.        ]
 [0.43091335 0.40487805 0.47368421 0.73333333 0.73684211 0.
  0.18181818 0.13846154 0.        ]
 [0.24824356 0.26097561 0.73684211 0.16666667 0.10526316 1.
  0.90909091 0.86153846 0.125     ]
 [0.67681499 0.72926829 1.         0.43333333 0.39473684 0.
  0.03030303 0.01538462 0.25      ]
 [0.15925059 0.17560976 0.         0.93333333 0.84210526 1.
  0.54545455 0.58461538 0.375     ]
 [0.92037471 0.96341463 0.21052632 0.3        0.26315789 0.
  0.66666667 0.64615385 0.5       ]
 [0.3793911  0.39268293 0.47368421 0.46666667 0.47368421 1.
  0.42424242 0.46153846 0.625     ]
 [0.60187354 0.65121951 0.73684211 0.66666667 0.65789474 0.
  0.24242424 0.26153846 0.75      ]
 [0.         0.         1.         0.2        0.15789474 1.
  0.63636364 0.67692308 0.875     ]
 [0.74004684 0.79512195 0.         0.4        0.42105263 0.
  0.87878788 0.83076923 1.        ]
 [0.49882904 0.51707317 0.21052632 0.9        0.86842105 1.
  0.3030303  0.33846154 0.        ]]


This rescaled feature now lies between 0 and 1.

One more example of **Min-Max Scaling:**

In [87]:
# Select numerical columns for scaling
numerical_cols = df[['feature1', 'feature2']]

# Keep categorical and target columns separate
categorical_cols = df[['categorical_column', 'target']]

In [88]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the scaler
scaler = MinMaxScaler()

# Fit and transform the numerical columns
numerical_scaled = scaler.fit_transform(numerical_cols)

# Convert the scaled data back to a DataFrame
numerical_scaled_df = pd.DataFrame(numerical_scaled, columns=numerical_cols.columns)

In [89]:
# Combine scaled numerical data with the categorical columns
df_scaled = pd.concat([numerical_scaled_df, categorical_cols.reset_index(drop=True)], axis=1)

# Display the final DataFrame
print(df_scaled)

    feature1  feature2 categorical_column  target
0   0.187354  0.204878                low       1
1   0.341920       NaN             medium       0
2        NaN       NaN               high       0
3   0.644028  0.817073          very_high       1
4   0.028103  0.014634                low       1
5   1.000000  0.568293             medium       0
6   0.381733       NaN               high       0
7   0.557377  0.412195          very_high       1
8   0.283372  0.282927                low       0
9   0.878220  0.934146             medium       1
10  0.114754  0.173171               high       0
11  0.482436  0.507317          very_high       1
12       NaN       NaN                low       0
13  0.709602  0.743902             medium       1
14  0.070258  0.070732               high       0
15  0.437939  0.456098          very_high       1
16  0.824356  0.660976                low       0
17  0.622951       NaN             medium       1
18  0.229508  0.268293               high       0
19  0.517564  0.546341          very_high       1
20  0.325527  0.363415                low       0
21  0.718970  0.782927             medium       1
22  0.147541  0.141463               high       0
23  0.932084  1.000000          very_high       1
24  0.398126  0.421951                low       0
25  0.594848  0.624390             medium       1
26  0.039813  0.041463               high       0
27  0.775176  0.829268          very_high       1
28  0.466042  0.475610                low       0
29  0.217799  0.224390             medium       1
30  0.660422  0.692683               high       0
31       NaN       NaN          very_high       1
32  0.297424  0.336585                low       0
33  0.840749  0.885366             medium       1
34  0.098361  0.109756               high       0
35  0.533958  0.585366          very_high       1
36  0.430913  0.404878                low       0
37  0.248244  0.260976             medium       1
38  0.676815  0.729268               high       0
39  0.159251  0.175610          very_high       1
40  0.920375  0.963415                low       0
41  0.379391  0.392683             medium       1
42  0.601874  0.651220               high       0
43  0.000000  0.000000          very_high       1
44  0.740047  0.795122                low       0
45  0.498829  0.517073             medium       1

**Use Case:**
- Use Min-Max Scaling when you want all your features to have the same scale (e.g., in algorithms like KNN, SVM).
- Particularly useful when the data is distributed across a known and fixed range.


#### **Z-Score Normalization (Standardization)**

**Z-Score Normalization** (or standardization) rescales the data to have a mean of 0 and a standard deviation of 1. This technique is useful when the data follows a Gaussian (normal) distribution but not necessarily bounded.

**Formula:**
$$
X' = \frac{X - \mu}{\sigma}
$$
Where:
- $\mu$ is the mean of the feature.
- $\sigma$ is the standard deviation of the feature.

**Example:**

Suppose you have a feature with values [10, 50, 100, 150, 200]. Applying Z-Score Normalization will adjust the data to have a mean of 0 and a standard deviation of 1.

In [91]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
standardized_data = scaler.fit_transform(numerical_df)

print(standardized_data)

[[-1.02032742 -0.96688656 -1.2902465  -1.79679815 -1.41296754  1.
  -1.43265691 -1.52419956 -1.49378879]
 [-0.45321242         nan -0.70979331 -0.02059368  0.86601237 -1.
  -0.24093507 -0.31743227 -1.11204277]
 [        nan         nan  0.01577318  0.80830175  0.13673879 -1.
   0.95078677  0.88933502 -0.73029674]
 [ 0.65523964  1.2111572   0.74133968  1.7556108   1.77760433  1.
   2.14250862  2.09610232 -0.34855072]
 [-1.60462773 -1.64372884  1.46690617 -0.8494891  -0.95717156  1.
  -1.07514036 -1.22250773  0.03319531]
 [ 1.96132269  0.32605575 -1.2902465  -0.37583457 -0.22789799 -1.
  -0.59845162 -0.43810899  0.41494133]
 [-0.30713734         nan -0.70979331  1.16354264  1.32180835 -1.
   0.35492585  0.40662811  0.79668736]
 [ 0.33731153 -0.22930202  0.01577318  0.33464722  0.31905719  1.
   0.11658148 -0.01574044  1.17843338]
 [-0.66802871 -0.68920767  0.74133968 -1.20472999 -1.13948996 -1.
  -0.83679599 -0.86047755  1.56017941]
 [ 1.5145048   1.62767553  1.46690617 -0.61266183 -0.68369397  1.
   0.59327022  0.7686583  -1.49378879]
 [-1.28669962 -1.0796936  -1.2902465   1.51878353  1.04833076 -1.
  -1.19431254 -1.40352283 -1.11204277]
 [ 0.06234668  0.10911912 -0.70979331  0.57147448  0.68369397  1.
  -0.47927944 -0.2570939  -0.73029674]
 [        nan         nan  0.74133968 -1.55997088 -1.68644513 -1.
  -0.95596817 -1.04149264 -0.34855072]
 [ 0.89583389  0.95083325  1.46690617  0.09781996 -0.0455796   1.
   0.83161459  1.01001175  0.03319531]
 [-1.44996    -1.44414714 -1.2902465   1.04512901  1.59528594 -1.
  -0.7176238  -0.61912409  0.41494133]
 [-0.1009137  -0.07310764 -0.70979331 -0.73107546 -0.77485317  1.
  -0.12176288  0.16527465  0.79668736]
 [ 1.31687382  0.65579943  0.01577318 -0.25742094 -0.41021638 -1.
   1.30830333  1.19102685  1.17843338]
 [ 0.57790578         nan  0.74133968  1.4003699   0.77485317  1.
  -1.31348473 -1.58453792  1.56017941]
 [-0.86565969 -0.74127246  1.46690617 -1.08631636 -1.23064915 -1.
  -0.36010725 -0.13641717 -1.49378879]
 [ 0.19123646  0.24795857 -1.2902465   0.45306085  0.50137558  1.
   0.47409804  0.5876432  -1.11204277]
 [-0.51336098 -0.40285132 -0.70979331 -0.4942482  -0.50137558 -1.
   0.23575367  0.22561302 -0.73029674]
 [ 0.93020449  1.08967269  0.01577318  0.92671538  1.23064915  1.
   1.06995896  0.94967339 -0.34855072]
 [-1.1664025  -1.19250065  0.74133968 -1.32314362 -1.50412674 -1.
  -0.0025907   0.04459792  0.03319531]
 [ 1.71213579  1.86196709  1.46690617  0.21623359  0.22789799  1.
   0.71244241  0.82899666  0.41494133]
 [-0.24698878 -0.19459216 -1.2902465   1.28195627  1.41296754 -1.
  -1.55182909 -1.70521465  0.79668736]
 [ 0.47479396  0.52563745 -0.70979331 -1.44155725 -1.32180835  1.
  -0.24093507 -0.07607881  1.17843338]
 [-1.56166447 -1.54827672  0.01577318  0.68988811  0.95717156 -1.
   1.18913114  1.13068848  1.56017941]
 [ 1.13642813  1.25454453  0.74133968 -0.13900731 -0.13673879  1.
   1.5466477   1.37204194 -1.49378879]
 [ 0.00219812 -0.00368792  1.46690617 -0.96790273 -0.86601237 -1.
  -1.79017346 -1.82589138 -1.11204277]
 [-0.90862295 -0.89746683 -1.2902465   1.63719717  1.50412674  1.
   1.42747551  1.25136521 -0.73029674]
 [ 0.7153882   0.76860648 -0.70979331 -1.67838452 -1.59528594 -1.
  -0.47927944 -0.37777063 -0.34855072]
 [        nan         nan  0.01577318  0.33464722  0.41021638  1.
   0.11658148  0.34628974  0.03319531]
 [-0.6164728  -0.49830344  0.74133968 -0.61266183 -0.59253478 -1.
  -0.95596817 -0.92081591  0.41494133]
 [ 1.37702238  1.45412622  1.46690617  1.16354264  1.13948996  1.
   0.95078677  0.88933502  0.79668736]
 [-1.34684818 -1.3053077  -1.2902465  -0.8494891  -1.04833076 -1.
  -0.7176238  -0.55878572  1.17843338]
 [ 0.25138502  0.38679801 -0.70979331  0.09781996  0.0455796   1.
  -0.0025907   0.10493629  1.56017941]
 [-0.12669165 -0.25533441  0.01577318  0.80830175  0.86601237 -1.
  -1.07514036 -1.2828461  -1.49378879]
 [-0.79691848 -0.76730486  0.74133968 -1.20472999 -1.32180835  1.
   1.78499206  1.55305703 -1.11204277]
 [ 0.77553677  0.89876845  1.46690617 -0.25742094 -0.31905719 -1.
  -1.67100128 -1.76555301 -0.73029674]
 [-1.12343924 -1.07101614 -1.2902465   1.51878353  1.23064915  1.
   0.35492585  0.46696647 -0.34855072]
 [ 1.66917253  1.73180511 -0.70979331 -0.73107546 -0.77485317 -1.
   0.83161459  0.70831993  0.03319531]
 [-0.31572999 -0.29872174  0.01577318 -0.13900731 -0.0455796   1.
  -0.12176288 -0.01574044  0.41494133]
 [ 0.50057191  0.62108957  0.74133968  0.57147448  0.59253478 -1.
  -0.83679599 -0.80013918  0.79668736]
 [-1.70773955 -1.69579363  1.46690617 -1.08631636 -1.13948996  1.
   0.71244241  0.82899666  1.17843338]
 [ 1.00753836  1.13306001 -1.2902465  -0.37583457 -0.22789799 -1.
   1.66581988  1.43238031  1.56017941]
 [ 0.12249524  0.14382899 -0.70979331  1.4003699   1.32180835  1.
  -0.59845162 -0.49844736 -1.49378879]]


One more example of **Z-Score Normalization (Standardization):**

In [92]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_standardized = scaler.fit_transform(numerical_cols)

This rescaled feature now has a mean of 0 and a standard deviation of 1.

**Use Case:**
- Use Z-Score Normalization when your data follows a normal distribution.
- It's the default choice for many machine learning models, especially those assuming normally distributed data.


#### **Robust Scaling**
**Robust Scaling** uses the median and interquartile range (IQR) for scaling, which makes it robust to outliers. Unlike Min-Max Scaling and Z-Score Normalization, Robust Scaling is less influenced by extreme values in the data.

**Formula:**

$$X'=\frac{X - \text{median}(X)}{\text{IQR}(X)}$$

Where:
- $\text{IQR}(X)$ is the range between the 25th percentile ($Q1$) and the 75th percentile ($Q3$).

**Example:**

Suppose you have a feature with values [10, 50, 100, 150, 200]. Robust Scaling will adjust the data based on the median and $\text{IQR}$.

In [95]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
robust_scaled_data = scaler.fit_transform(numerical_df)

print(robust_scaled_data)

[[-0.64850136 -0.5799458  -0.9        -1.05454545 -0.8         0.5
  -0.85185185 -0.97142857 -1.        ]
 [-0.28882834         nan -0.5         0.03636364  0.53333333 -0.5
  -0.11111111 -0.20952381 -0.75      ]
 [        nan         nan  0.          0.54545455  0.10666667 -0.5
   0.62962963  0.55238095 -0.5       ]
 [ 0.41416894  0.7804878   0.5         1.12727273  1.06666667  0.5
   1.37037037  1.31428571 -0.25      ]
 [-1.01907357 -1.00271003  1.         -0.47272727 -0.53333333  0.5
  -0.62962963 -0.78095238  0.        ]
 [ 1.24250681  0.22764228 -0.9        -0.18181818 -0.10666667 -0.5
  -0.33333333 -0.28571429  0.25      ]
 [-0.19618529         nan -0.5         0.76363636  0.8        -0.5
   0.25925926  0.24761905  0.5       ]
 [ 0.21253406 -0.11924119  0.          0.25454545  0.21333333  0.5
   0.11111111 -0.01904762  0.75      ]
 [-0.42506812 -0.40650407  0.5        -0.69090909 -0.64       -0.5
  -0.48148148 -0.55238095  1.        ]
 [ 0.95912807  1.04065041  1.         -0.32727273 -0.37333333  0.5
   0.40740741  0.47619048 -1.        ]
 [-0.81743869 -0.6504065  -0.9         0.98181818  0.64       -0.5
  -0.7037037  -0.8952381  -0.75      ]
 [ 0.03814714  0.09214092 -0.5         0.4         0.42666667  0.5
  -0.25925926 -0.17142857 -0.5       ]
 [        nan         nan  0.5        -0.90909091 -0.96       -0.5
  -0.55555556 -0.66666667 -0.25      ]
 [ 0.56675749  0.61788618  1.          0.10909091  0.          0.5
   0.55555556  0.62857143  0.        ]
 [-0.92098093 -0.87804878 -0.9         0.69090909  0.96       -0.5
  -0.40740741 -0.4         0.25      ]
 [-0.0653951  -0.02168022 -0.5        -0.4        -0.42666667  0.5
  -0.03703704  0.0952381   0.5       ]
 [ 0.83378747  0.43360434  0.         -0.10909091 -0.21333333 -0.5
   0.85185185  0.74285714  0.75      ]
 [ 0.36512262         nan  0.5         0.90909091  0.48        0.5
  -0.77777778 -1.00952381  1.        ]
 [-0.55040872 -0.43902439  1.         -0.61818182 -0.69333333 -0.5
  -0.18518519 -0.0952381  -1.        ]
 [ 0.11989101  0.17886179 -0.9         0.32727273  0.32        0.5
   0.33333333  0.36190476 -0.75      ]
 [-0.32697548 -0.22764228 -0.5        -0.25454545 -0.26666667 -0.5
   0.18518519  0.13333333 -0.5       ]
 [ 0.58855586  0.70460705  0.          0.61818182  0.74666667  0.5
   0.7037037   0.59047619 -0.25      ]
 [-0.74114441 -0.72086721  0.5        -0.76363636 -0.85333333 -0.5
   0.03703704  0.01904762  0.        ]
 [ 1.08446866  1.18699187  1.          0.18181818  0.16        0.5
   0.48148148  0.51428571  0.25      ]
 [-0.15803815 -0.09756098 -0.9         0.83636364  0.85333333 -0.5
  -0.92592593 -1.08571429  0.5       ]
 [ 0.29972752  0.35230352 -0.5        -0.83636364 -0.74666667  0.5
  -0.11111111 -0.05714286  0.75      ]
 [-0.99182561 -0.94308943  0.          0.47272727  0.58666667 -0.5
   0.77777778  0.7047619   1.        ]
 [ 0.71934605  0.80758808  0.5        -0.03636364 -0.05333333  0.5
   1.          0.85714286 -1.        ]
 [ 0.          0.02168022  1.         -0.54545455 -0.48       -0.5
  -1.07407407 -1.16190476 -0.75      ]
 [-0.57765668 -0.53658537 -0.9         1.05454545  0.90666667  0.5
   0.92592593  0.78095238 -0.5       ]
 [ 0.45231608  0.50406504 -0.5        -0.98181818 -0.90666667 -0.5
  -0.25925926 -0.24761905 -0.25      ]
 [        nan         nan  0.          0.25454545  0.26666667  0.5
   0.11111111  0.20952381  0.        ]
 [-0.39237057 -0.28726287  0.5        -0.32727273 -0.32       -0.5
  -0.55555556 -0.59047619  0.25      ]
 [ 0.8719346   0.93224932  1.          0.76363636  0.69333333  0.5
   0.62962963  0.55238095  0.5       ]
 [-0.85558583 -0.79132791 -0.9        -0.47272727 -0.58666667 -0.5
  -0.40740741 -0.36190476  0.75      ]
 [ 0.15803815  0.26558266 -0.5         0.10909091  0.05333333  0.5
   0.03703704  0.05714286  1.        ]
 [-0.08174387 -0.13550136  0.          0.54545455  0.53333333 -0.5
  -0.62962963 -0.81904762 -1.        ]
 [-0.50681199 -0.45528455  0.5        -0.69090909 -0.74666667  0.5
   1.14814815  0.97142857 -0.75      ]
 [ 0.49046322  0.58536585  1.         -0.10909091 -0.16       -0.5
  -1.         -1.12380952 -0.5       ]
 [-0.71389646 -0.64498645 -0.9         0.98181818  0.74666667  0.5
   0.25925926  0.28571429 -0.25      ]
 [ 1.05722071  1.10569106 -0.5        -0.4        -0.42666667 -0.5
   0.55555556  0.43809524  0.        ]
 [-0.20163488 -0.16260163  0.         -0.03636364  0.          0.5
  -0.03703704 -0.01904762  0.25      ]
 [ 0.31607629  0.41192412  0.5         0.4         0.37333333 -0.5
  -0.48148148 -0.51428571  0.5       ]
 [-1.08446866 -1.03523035  1.         -0.61818182 -0.64        0.5
   0.48148148  0.51428571  0.75      ]
 [ 0.63760218  0.73170732 -0.9        -0.18181818 -0.10666667 -0.5
   1.07407407  0.8952381   1.        ]
 [ 0.07629428  0.11382114 -0.5         0.90909091  0.8         0.5
  -0.33333333 -0.32380952 -1.        ]]

This scaling ensures that outliers have less influence on the scaled data.


One more example of **Robust Scaling:**

In [96]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
df_robust_scaled = scaler.fit_transform(numerical_cols)


**Use Case:**
- Use Robust Scaling when your data contains outliers or follows a non-Gaussian distribution.
- Ideal for situations where the data is skewed or contains extreme values that should not heavily influence the scaling.

###2.3. When to Use Each Technique

- **Min-Max Scaling:**
  - Use when you want to bring all features into the same scale, especially for algorithms that rely on distance metrics (e.g., KNN, SVM).
  - Suitable for data with known bounds.

- **Z-Score Normalization (Standardization):**
  - Use when your data follows a normal distribution, or when using models that assume normally distributed data (e.g., linear regression, logistic regression).
  - It's also a good general-purpose scaler when you don't have specific needs for Min-Max Scaling or Robust Scaling.

- **Robust Scaling:**
  - Use when your data contains outliers or is heavily skewed.
  - Ideal for datasets with features that have varying scales and are not normally distributed.

Scaling and normalization are critical steps in the data preprocessing pipeline. The choice of technique depends on the nature of your data and the requirements of the machine learning algorithm you are using. By appropriately scaling your data, you ensure that your models perform optimally and converge more quickly during training.

**c. Choosing the Right Scaling Technique:**
- **Min-Max Scaling:** Use when you know the boundaries of your data or when the algorithm requires data in a specific range.
- **Z-Score Normalization:** Suitable for normally distributed data or when you want to standardize features to have equal importance.
- **Robust Scaling:** Best when dealing with data that has outliers.

##3. Introduction to Feature Engineering

Feature engineering is a crucial step in the data preprocessing pipeline. It involves transforming raw data into features that better represent the underlying problem to the predictive models. Good feature engineering can significantly improve the performance of machine learning models by providing them with the most relevant and informative input data.

###3.1. Definition and Importance

**Feature Engineering** refers to the process of selecting, modifying, or creating new features from raw data to improve the performance of machine learning models. The goal is to create features that capture the underlying patterns in the data more effectively than the original raw data. Proper feature engineering can lead to simpler models, improved accuracy, and reduced training times.

###3.2. Techniques in Feature Engineering

#### **Creating New Features**

Creating new features involves deriving new variables from existing ones that better represent the underlying structure of the data. This could involve mathematical transformations, aggregations, or domain-specific operations.

**Example 1: Mathematical Transformations**

Suppose you have a dataset with the `height` and `weight` of individuals. You can create a new feature, Body Mass Index (BMI), which is a better indicator of health than either `height` or `weight` alone.

In [98]:
df.head(4)

,feature1,feature2,feature,height,weight,date,color,target,age,income,x,categorical_column
0,25.5,30.2,10,1.60,55,2024-01-01,red,1,25,30000,2,low
1,32.1,NaN,50,1.75,80,2024-06-15,blue,0,35,50000,3,medium
2,NaN,NaN,100,1.82,72,2024-12-31,green,0,45,70000,4,high
3,45.0,55.3,150,1.90,90,2024-03-10,red,1,55,90000,5,very_high

In [99]:
# Creating a new feature: BMI
df['BMI'] = df['weight'] / (df['height'] ** 2)

print(df)

    feature1  feature2  feature  height  weight        date  color  target  \
0       25.5      30.2       10    1.60      55  2024-01-01    red       1
1       32.1       NaN       50    1.75      80  2024-06-15   blue       0
2        NaN       NaN      100    1.82      72  2024-12-31  green       0
3       45.0      55.3      150    1.90      90  2024-03-10    red       1
4       18.7      22.4      200    1.68      60  2024-07-22   blue       1
5       60.2      45.1       10    1.72      68  2024-02-14  green       0
6       33.8       NaN       50    1.85      85  2024-09-05    red       0
7       41.3      38.7      100    1.78      74  2024-04-18   blue       1
8       29.6      33.4      150    1.65      58  2024-11-30  green       0
9       55.0      60.1      200    1.70      63  2024-08-12    red       1
10      22.4      28.9       10    1.88      82  2024-05-25   blue       0
11      38.1      42.6       50    1.80      78  2024-10-08  green       1
12       NaN       NaN      150    1.62      52  2024-12-01    red       0
13      47.8      52.3      200    1.76      70  2024-03-29   blue       1
14      20.5      24.7       10    1.84      88  2024-09-17  green       0
15      36.2      40.5       50    1.69      62  2024-06-08    red       1
16      52.7      48.9      100    1.73      66  2024-01-22   blue       0
17      44.1       NaN      150    1.87      79  2024-04-05  green       1
18      27.3      32.8      200    1.66      57  2024-10-15    red       0
19      39.6      44.2       10    1.79      76  2024-07-30   blue       1
20      31.4      36.7       50    1.71      65  2024-05-12  green       0
21      48.2      53.9      100    1.83      84  2024-02-28    red       1
22      23.8      27.6      150    1.64      54  2024-08-20   blue       0
23      57.3      62.8      200    1.77      73  2024-11-11  green       1
24      34.5      39.1       10    1.86      86  2024-03-03    red       0
25      42.9      47.4       50    1.63      56  2024-12-20   blue       1
26      19.2      23.5      100    1.81      81  2024-09-09  green       0
27      50.6      55.8      150    1.74      69  2024-06-14    red       1
28      37.4      41.3      200    1.67      61  2024-10-28   blue       0
29      26.8      31.0       10    1.89      87  2024-01-07  green       1
30      45.7      50.2       50    1.61      53  2024-04-22    red       0
31       NaN       NaN      100    1.78      75  2024-07-15   blue       1
32      30.2      35.6      150    1.70      64  2024-02-09  green       0
33      53.4      58.1      200    1.85      83  2024-11-03    red       1
34      21.7      26.3       10    1.68      59  2024-08-28   blue       0
35      40.3      45.8       50    1.76      71  2024-05-19  green       1
36      35.9      38.4      100    1.82      80  2024-12-14    red       0
37      28.1      32.5      150    1.65      56  2024-03-17   blue       1
38      46.4      51.7      200    1.73      67  2024-09-25  green       0
39      24.3      29.0       10    1.88      84  2024-10-02    red       1
40      56.8      61.3       50    1.69      62  2024-07-08   blue       0
41      33.7      37.9      100    1.74      70  2024-01-30  green       1
42      43.2      48.5      150    1.80      77  2024-04-12    red       0
43      17.5      21.8      200    1.66      58  2024-06-25   blue       1
44      49.1      54.4       10    1.72      68  2024-08-16  green       0
45      38.8      43.0       50    1.87      85  2024-11-28    red       1

    age  income   x categorical_column        BMI
0    25   30000   2                low  21.484375
1    35   50000   3             medium  26.122449
2    45   70000   4               high  21.736505
3    55   90000   5          very_high  24.930748
4    28   35000   6                low  21.258503
5    32   48000   7             medium  22.985398
6    40   62000   8               high  24.835646
7    38   55000   9          very_high  23.355637
8    30   41000  10                low  21.303949
9    42   68000   2             medium  21.799308
10   27   32000   3               high  23.200543
11   33   51000   4          very_high  24.074074
12   29   38000   5                low  19.814053
13   44   72000   6             medium  22.598140
14   31   45000   7               high  25.992439
15   36   58000   8          very_high  21.707923
16   48   75000   9                low  22.052190
17   26   29000  10             medium  22.591438
18   34   53000   2               high  20.685150
19   41   65000   3          very_high  23.719609
20   39   59000   4                low  22.229062
21   46   71000   5             medium  25.082863
22   37   56000   6               high  20.077335
23   43   69000   7          very_high  23.301095
24   24   27000   8                low  24.858365
25   35   54000   9             medium  21.077195
26   47   74000  10               high  24.724520
27   50   78000   2          very_high  22.790329
28   22   25000   3                low  21.872423
29   49   76000   4             medium  24.355421
30   33   49000   5               high  20.446742
31   38   61000   6          very_high  23.671254
32   29   40000   7                low  22.145329
33   45   70000   8             medium  24.251278
34   31   46000   9               high  20.904195
35   37   57000  10          very_high  22.920971
36   28   34000   2                low  24.151673
37   52   81000   3             medium  20.569330
38   23   26000   4               high  22.386314
39   40   63000   5          very_high  23.766410
40   44   67000   6                low  21.707923
41   36   55000   7             medium  23.120624
42   30   42000   8               high  23.765432
43   43   69000   9          very_high  21.048048
44   51   79000  10                low  22.985398
45   32   47000   2             medium  24.307244

**Example 2: Date-Time Features**

Suppose you have a `date` feature. You can create new features such as `day_of_week`, `month`, or `year` to capture patterns that occur over time.

In [100]:
# Convert to datetime
df['date'] = pd.to_datetime(df['date'])

# Creating new date-time features
df['day_of_week'] = df['date'].dt.day_name()
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

print(df)

    feature1  feature2  feature  height  weight       date  color  target  \
0       25.5      30.2       10    1.60      55 2024-01-01    red       1
1       32.1       NaN       50    1.75      80 2024-06-15   blue       0
2        NaN       NaN      100    1.82      72 2024-12-31  green       0
3       45.0      55.3      150    1.90      90 2024-03-10    red       1
4       18.7      22.4      200    1.68      60 2024-07-22   blue       1
5       60.2      45.1       10    1.72      68 2024-02-14  green       0
6       33.8       NaN       50    1.85      85 2024-09-05    red       0
7       41.3      38.7      100    1.78      74 2024-04-18   blue       1
8       29.6      33.4      150    1.65      58 2024-11-30  green       0
9       55.0      60.1      200    1.70      63 2024-08-12    red       1
10      22.4      28.9       10    1.88      82 2024-05-25   blue       0
11      38.1      42.6       50    1.80      78 2024-10-08  green       1
12       NaN       NaN      150    1.62      52 2024-12-01    red       0
13      47.8      52.3      200    1.76      70 2024-03-29   blue       1
14      20.5      24.7       10    1.84      88 2024-09-17  green       0
15      36.2      40.5       50    1.69      62 2024-06-08    red       1
16      52.7      48.9      100    1.73      66 2024-01-22   blue       0
17      44.1       NaN      150    1.87      79 2024-04-05  green       1
18      27.3      32.8      200    1.66      57 2024-10-15    red       0
19      39.6      44.2       10    1.79      76 2024-07-30   blue       1
20      31.4      36.7       50    1.71      65 2024-05-12  green       0
21      48.2      53.9      100    1.83      84 2024-02-28    red       1
22      23.8      27.6      150    1.64      54 2024-08-20   blue       0
23      57.3      62.8      200    1.77      73 2024-11-11  green       1
24      34.5      39.1       10    1.86      86 2024-03-03    red       0
25      42.9      47.4       50    1.63      56 2024-12-20   blue       1
26      19.2      23.5      100    1.81      81 2024-09-09  green       0
27      50.6      55.8      150    1.74      69 2024-06-14    red       1
28      37.4      41.3      200    1.67      61 2024-10-28   blue       0
29      26.8      31.0       10    1.89      87 2024-01-07  green       1
30      45.7      50.2       50    1.61      53 2024-04-22    red       0
31       NaN       NaN      100    1.78      75 2024-07-15   blue       1
32      30.2      35.6      150    1.70      64 2024-02-09  green       0
33      53.4      58.1      200    1.85      83 2024-11-03    red       1
34      21.7      26.3       10    1.68      59 2024-08-28   blue       0
35      40.3      45.8       50    1.76      71 2024-05-19  green       1
36      35.9      38.4      100    1.82      80 2024-12-14    red       0
37      28.1      32.5      150    1.65      56 2024-03-17   blue       1
38      46.4      51.7      200    1.73      67 2024-09-25  green       0
39      24.3      29.0       10    1.88      84 2024-10-02    red       1
40      56.8      61.3       50    1.69      62 2024-07-08   blue       0
41      33.7      37.9      100    1.74      70 2024-01-30  green       1
42      43.2      48.5      150    1.80      77 2024-04-12    red       0
43      17.5      21.8      200    1.66      58 2024-06-25   blue       1
44      49.1      54.4       10    1.72      68 2024-08-16  green       0
45      38.8      43.0       50    1.87      85 2024-11-28    red       1

    age  income   x categorical_column        BMI day_of_week  month  year
0    25   30000   2                low  21.484375      Monday      1  2024
1    35   50000   3             medium  26.122449    Saturday      6  2024
2    45   70000   4               high  21.736505     Tuesday     12  2024
3    55   90000   5          very_high  24.930748      Sunday      3  2024
4    28   35000   6                low  21.258503      Monday      7  2024
5    32   48000   7             medium  22.985398   Wednesday      2  2024
6    40   62000   8               high  24.835646    Thursday      9  2024
7    38   55000   9          very_high  23.355637    Thursday      4  2024
8    30   41000  10                low  21.303949    Saturday     11  2024
9    42   68000   2             medium  21.799308      Monday      8  2024
10   27   32000   3               high  23.200543    Saturday      5  2024
11   33   51000   4          very_high  24.074074     Tuesday     10  2024
12   29   38000   5                low  19.814053      Sunday     12  2024
13   44   72000   6             medium  22.598140      Friday      3  2024
14   31   45000   7               high  25.992439     Tuesday      9  2024
15   36   58000   8          very_high  21.707923    Saturday      6  2024
16   48   75000   9                low  22.052190      Monday      1  2024
17   26   29000  10             medium  22.591438      Friday      4  2024
18   34   53000   2               high  20.685150     Tuesday     10  2024
19   41   65000   3          very_high  23.719609     Tuesday      7  2024
20   39   59000   4                low  22.229062      Sunday      5  2024
21   46   71000   5             medium  25.082863   Wednesday      2  2024
22   37   56000   6               high  20.077335     Tuesday      8  2024
23   43   69000   7          very_high  23.301095      Monday     11  2024
24   24   27000   8                low  24.858365      Sunday      3  2024
25   35   54000   9             medium  21.077195      Friday     12  2024
26   47   74000  10               high  24.724520      Monday      9  2024
27   50   78000   2          very_high  22.790329      Friday      6  2024
28   22   25000   3                low  21.872423      Monday     10  2024
29   49   76000   4             medium  24.355421      Sunday      1  2024
30   33   49000   5               high  20.446742      Monday      4  2024
31   38   61000   6          very_high  23.671254      Monday      7  2024
32   29   40000   7                low  22.145329      Friday      2  2024
33   45   70000   8             medium  24.251278      Sunday     11  2024
34   31   46000   9               high  20.904195   Wednesday      8  2024
35   37   57000  10          very_high  22.920971      Sunday      5  2024
36   28   34000   2                low  24.151673    Saturday     12  2024
37   52   81000   3             medium  20.569330      Sunday      3  2024
38   23   26000   4               high  22.386314   Wednesday      9  2024
39   40   63000   5          very_high  23.766410   Wednesday     10  2024
40   44   67000   6                low  21.707923      Monday      7  2024
41   36   55000   7             medium  23.120624     Tuesday      1  2024
42   30   42000   8               high  23.765432      Friday      4  2024
43   43   69000   9          very_high  21.048048     Tuesday      6  2024
44   51   79000  10                low  22.985398      Friday      8  2024
45   32   47000   2             medium  24.307244    Thursday     11  2024

#### **Encoding Categorical Variables**

Machine learning algorithms generally require numerical input. Therefore, categorical variables must be converted into numerical format. There are several techniques to encode categorical variables:

**a. One-Hot Encoding**

One-hot encoding converts each category into a new binary column. This method is suitable when there are a limited number of categories.

**Example:**

In [101]:
# One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['color'])

print(df_encoded)

    feature1  feature2  feature  height  weight       date  target  age  \
0       25.5      30.2       10    1.60      55 2024-01-01       1   25
1       32.1       NaN       50    1.75      80 2024-06-15       0   35
2        NaN       NaN      100    1.82      72 2024-12-31       0   45
3       45.0      55.3      150    1.90      90 2024-03-10       1   55
4       18.7      22.4      200    1.68      60 2024-07-22       1   28
5       60.2      45.1       10    1.72      68 2024-02-14       0   32
6       33.8       NaN       50    1.85      85 2024-09-05       0   40
7       41.3      38.7      100    1.78      74 2024-04-18       1   38
8       29.6      33.4      150    1.65      58 2024-11-30       0   30
9       55.0      60.1      200    1.70      63 2024-08-12       1   42
10      22.4      28.9       10    1.88      82 2024-05-25       0   27
11      38.1      42.6       50    1.80      78 2024-10-08       1   33
12       NaN       NaN      150    1.62      52 2024-12-01       0   29
13      47.8      52.3      200    1.76      70 2024-03-29       1   44
14      20.5      24.7       10    1.84      88 2024-09-17       0   31
15      36.2      40.5       50    1.69      62 2024-06-08       1   36
16      52.7      48.9      100    1.73      66 2024-01-22       0   48
17      44.1       NaN      150    1.87      79 2024-04-05       1   26
18      27.3      32.8      200    1.66      57 2024-10-15       0   34
19      39.6      44.2       10    1.79      76 2024-07-30       1   41
20      31.4      36.7       50    1.71      65 2024-05-12       0   39
21      48.2      53.9      100    1.83      84 2024-02-28       1   46
22      23.8      27.6      150    1.64      54 2024-08-20       0   37
23      57.3      62.8      200    1.77      73 2024-11-11       1   43
24      34.5      39.1       10    1.86      86 2024-03-03       0   24
25      42.9      47.4       50    1.63      56 2024-12-20       1   35
26      19.2      23.5      100    1.81      81 2024-09-09       0   47
27      50.6      55.8      150    1.74      69 2024-06-14       1   50
28      37.4      41.3      200    1.67      61 2024-10-28       0   22
29      26.8      31.0       10    1.89      87 2024-01-07       1   49
30      45.7      50.2       50    1.61      53 2024-04-22       0   33
31       NaN       NaN      100    1.78      75 2024-07-15       1   38
32      30.2      35.6      150    1.70      64 2024-02-09       0   29
33      53.4      58.1      200    1.85      83 2024-11-03       1   45
34      21.7      26.3       10    1.68      59 2024-08-28       0   31
35      40.3      45.8       50    1.76      71 2024-05-19       1   37
36      35.9      38.4      100    1.82      80 2024-12-14       0   28
37      28.1      32.5      150    1.65      56 2024-03-17       1   52
38      46.4      51.7      200    1.73      67 2024-09-25       0   23
39      24.3      29.0       10    1.88      84 2024-10-02       1   40
40      56.8      61.3       50    1.69      62 2024-07-08       0   44
41      33.7      37.9      100    1.74      70 2024-01-30       1   36
42      43.2      48.5      150    1.80      77 2024-04-12       0   30
43      17.5      21.8      200    1.66      58 2024-06-25       1   43
44      49.1      54.4       10    1.72      68 2024-08-16       0   51
45      38.8      43.0       50    1.87      85 2024-11-28       1   32

    income   x categorical_column        BMI day_of_week  month  year  \
0    30000   2                low  21.484375      Monday      1  2024
1    50000   3             medium  26.122449    Saturday      6  2024
2    70000   4               high  21.736505     Tuesday     12  2024
3    90000   5          very_high  24.930748      Sunday      3  2024
4    35000   6                low  21.258503      Monday      7  2024
5    48000   7             medium  22.985398   Wednesday      2  2024
6    62000   8               high  24.835646    Thursday      9  2024
7    55000   9          very_high  23.355637    Thursday      4  2024
8    41000  10                low  21.303949    Saturday     11  2024
9    68000   2             medium  21.799308      Monday      8  2024
10   32000   3               high  23.200543    Saturday      5  2024
11   51000   4          very_high  24.074074     Tuesday     10  2024
12   38000   5                low  19.814053      Sunday     12  2024
13   72000   6             medium  22.598140      Friday      3  2024
14   45000   7               high  25.992439     Tuesday      9  2024
15   58000   8          very_high  21.707923    Saturday      6  2024
16   75000   9                low  22.052190      Monday      1  2024
17   29000  10             medium  22.591438      Friday      4  2024
18   53000   2               high  20.685150     Tuesday     10  2024
19   65000   3          very_high  23.719609     Tuesday      7  2024
20   59000   4                low  22.229062      Sunday      5  2024
21   71000   5             medium  25.082863   Wednesday      2  2024
22   56000   6               high  20.077335     Tuesday      8  2024
23   69000   7          very_high  23.301095      Monday     11  2024
24   27000   8                low  24.858365      Sunday      3  2024
25   54000   9             medium  21.077195      Friday     12  2024
26   74000  10               high  24.724520      Monday      9  2024
27   78000   2          very_high  22.790329      Friday      6  2024
28   25000   3                low  21.872423      Monday     10  2024
29   76000   4             medium  24.355421      Sunday      1  2024
30   49000   5               high  20.446742      Monday      4  2024
31   61000   6          very_high  23.671254      Monday      7  2024
32   40000   7                low  22.145329      Friday      2  2024
33   70000   8             medium  24.251278      Sunday     11  2024
34   46000   9               high  20.904195   Wednesday      8  2024
35   57000  10          very_high  22.920971      Sunday      5  2024
36   34000   2                low  24.151673    Saturday     12  2024
37   81000   3             medium  20.569330      Sunday      3  2024
38   26000   4               high  22.386314   Wednesday      9  2024
39   63000   5          very_high  23.766410   Wednesday     10  2024
40   67000   6                low  21.707923      Monday      7  2024
41   55000   7             medium  23.120624     Tuesday      1  2024
42   42000   8               high  23.765432      Friday      4  2024
43   69000   9          very_high  21.048048     Tuesday      6  2024
44   79000  10                low  22.985398      Friday      8  2024
45   47000   2             medium  24.307244    Thursday     11  2024

    color_blue  color_green  color_red
0        False        False       True
1         True        False      False
2        False         True      False
3        False        False       True
4         True        False      False
5        False         True      False
6        False        False       True
7         True        False      False
8        False         True      False
9        False        False       True
10        True        False      False
11       False         True      False
12       False        False       True
13        True        False      False
14       False         True      False
15       False        False       True
16        True        False      False
17       False         True      False
18       False        False       True
19        True        False      False
20       False         True      False
21       False        False       True
22        True        False      False
23       False         True      False
24       False        False       True
25        True        False      False
26       False         True      False
27       False        False       True
28        True        False      False
29       False         True      False
30       False        False       True
31        True        False      False
32       False         True      False
33       False        False       True
34        True        False      False
35       False         True      False
36       False        False       True
37        True        False      False
38       False         True      False
39       False        False       True
40        True        False      False
41       False         True      False
42       False        False       True
43        True        False      False
44       False         True      False
45       False        False       True

**b. Label Encoding**

Label encoding assigns a unique integer to each category. It is simple but assumes an ordinal relationship between the categories, which may not be appropriate for all cases.

**Example:**

In [102]:
from sklearn.preprocessing import LabelEncoder

# Label Encoding
encoder = LabelEncoder()
df['color_encoded'] = encoder.fit_transform(df['color'])

print(df)

    feature1  feature2  feature  height  weight       date  color  target  \
0       25.5      30.2       10    1.60      55 2024-01-01    red       1
1       32.1       NaN       50    1.75      80 2024-06-15   blue       0
2        NaN       NaN      100    1.82      72 2024-12-31  green       0
3       45.0      55.3      150    1.90      90 2024-03-10    red       1
4       18.7      22.4      200    1.68      60 2024-07-22   blue       1
5       60.2      45.1       10    1.72      68 2024-02-14  green       0
6       33.8       NaN       50    1.85      85 2024-09-05    red       0
7       41.3      38.7      100    1.78      74 2024-04-18   blue       1
8       29.6      33.4      150    1.65      58 2024-11-30  green       0
9       55.0      60.1      200    1.70      63 2024-08-12    red       1
10      22.4      28.9       10    1.88      82 2024-05-25   blue       0
11      38.1      42.6       50    1.80      78 2024-10-08  green       1
12       NaN       NaN      150    1.62      52 2024-12-01    red       0
13      47.8      52.3      200    1.76      70 2024-03-29   blue       1
14      20.5      24.7       10    1.84      88 2024-09-17  green       0
15      36.2      40.5       50    1.69      62 2024-06-08    red       1
16      52.7      48.9      100    1.73      66 2024-01-22   blue       0
17      44.1       NaN      150    1.87      79 2024-04-05  green       1
18      27.3      32.8      200    1.66      57 2024-10-15    red       0
19      39.6      44.2       10    1.79      76 2024-07-30   blue       1
20      31.4      36.7       50    1.71      65 2024-05-12  green       0
21      48.2      53.9      100    1.83      84 2024-02-28    red       1
22      23.8      27.6      150    1.64      54 2024-08-20   blue       0
23      57.3      62.8      200    1.77      73 2024-11-11  green       1
24      34.5      39.1       10    1.86      86 2024-03-03    red       0
25      42.9      47.4       50    1.63      56 2024-12-20   blue       1
26      19.2      23.5      100    1.81      81 2024-09-09  green       0
27      50.6      55.8      150    1.74      69 2024-06-14    red       1
28      37.4      41.3      200    1.67      61 2024-10-28   blue       0
29      26.8      31.0       10    1.89      87 2024-01-07  green       1
30      45.7      50.2       50    1.61      53 2024-04-22    red       0
31       NaN       NaN      100    1.78      75 2024-07-15   blue       1
32      30.2      35.6      150    1.70      64 2024-02-09  green       0
33      53.4      58.1      200    1.85      83 2024-11-03    red       1
34      21.7      26.3       10    1.68      59 2024-08-28   blue       0
35      40.3      45.8       50    1.76      71 2024-05-19  green       1
36      35.9      38.4      100    1.82      80 2024-12-14    red       0
37      28.1      32.5      150    1.65      56 2024-03-17   blue       1
38      46.4      51.7      200    1.73      67 2024-09-25  green       0
39      24.3      29.0       10    1.88      84 2024-10-02    red       1
40      56.8      61.3       50    1.69      62 2024-07-08   blue       0
41      33.7      37.9      100    1.74      70 2024-01-30  green       1
42      43.2      48.5      150    1.80      77 2024-04-12    red       0
43      17.5      21.8      200    1.66      58 2024-06-25   blue       1
44      49.1      54.4       10    1.72      68 2024-08-16  green       0
45      38.8      43.0       50    1.87      85 2024-11-28    red       1

    age  income   x categorical_column        BMI day_of_week  month  year  \
0    25   30000   2                low  21.484375      Monday      1  2024
1    35   50000   3             medium  26.122449    Saturday      6  2024
2    45   70000   4               high  21.736505     Tuesday     12  2024
3    55   90000   5          very_high  24.930748      Sunday      3  2024
4    28   35000   6                low  21.258503      Monday      7  2024
5    32   48000   7             medium  22.985398   Wednesday      2  2024
6    40   62000   8               high  24.835646    Thursday      9  2024
7    38   55000   9          very_high  23.355637    Thursday      4  2024
8    30   41000  10                low  21.303949    Saturday     11  2024
9    42   68000   2             medium  21.799308      Monday      8  2024
10   27   32000   3               high  23.200543    Saturday      5  2024
11   33   51000   4          very_high  24.074074     Tuesday     10  2024
12   29   38000   5                low  19.814053      Sunday     12  2024
13   44   72000   6             medium  22.598140      Friday      3  2024
14   31   45000   7               high  25.992439     Tuesday      9  2024
15   36   58000   8          very_high  21.707923    Saturday      6  2024
16   48   75000   9                low  22.052190      Monday      1  2024
17   26   29000  10             medium  22.591438      Friday      4  2024
18   34   53000   2               high  20.685150     Tuesday     10  2024
19   41   65000   3          very_high  23.719609     Tuesday      7  2024
20   39   59000   4                low  22.229062      Sunday      5  2024
21   46   71000   5             medium  25.082863   Wednesday      2  2024
22   37   56000   6               high  20.077335     Tuesday      8  2024
23   43   69000   7          very_high  23.301095      Monday     11  2024
24   24   27000   8                low  24.858365      Sunday      3  2024
25   35   54000   9             medium  21.077195      Friday     12  2024
26   47   74000  10               high  24.724520      Monday      9  2024
27   50   78000   2          very_high  22.790329      Friday      6  2024
28   22   25000   3                low  21.872423      Monday     10  2024
29   49   76000   4             medium  24.355421      Sunday      1  2024
30   33   49000   5               high  20.446742      Monday      4  2024
31   38   61000   6          very_high  23.671254      Monday      7  2024
32   29   40000   7                low  22.145329      Friday      2  2024
33   45   70000   8             medium  24.251278      Sunday     11  2024
34   31   46000   9               high  20.904195   Wednesday      8  2024
35   37   57000  10          very_high  22.920971      Sunday      5  2024
36   28   34000   2                low  24.151673    Saturday     12  2024
37   52   81000   3             medium  20.569330      Sunday      3  2024
38   23   26000   4               high  22.386314   Wednesday      9  2024
39   40   63000   5          very_high  23.766410   Wednesday     10  2024
40   44   67000   6                low  21.707923      Monday      7  2024
41   36   55000   7             medium  23.120624     Tuesday      1  2024
42   30   42000   8               high  23.765432      Friday      4  2024
43   43   69000   9          very_high  21.048048     Tuesday      6  2024
44   51   79000  10                low  22.985398      Friday      8  2024
45   32   47000   2             medium  24.307244    Thursday     11  2024

    color_encoded
0               2
1               0
2               1
3               2
4               0
5               1
6               2
7               0
8               1
9               2
10              0
11              1
12              2
13              0
14              1
15              2
16              0
17              1
18              2
19              0
20              1
21              2
22              0
23              1
24              2
25              0
26              1
27              2
28              0
29              1
30              2
31              0
32              1
33              2
34              0
35              1
36              2
37              0
38              1
39              2
40              0
41              1
42              2
43              0
44              1
45              2

**c. Target Encoding**

Target encoding involves replacing each category with the mean of the target variable for that category. This technique is useful when the categorical variable has a large number of levels.

**Example:**

In [103]:

# Target Encoding
df['color_encoded'] = df.groupby('color')['target'].transform('mean')

print(df)

    feature1  feature2  feature  height  weight       date  color  target  \
0       25.5      30.2       10    1.60      55 2024-01-01    red       1
1       32.1       NaN       50    1.75      80 2024-06-15   blue       0
2        NaN       NaN      100    1.82      72 2024-12-31  green       0
3       45.0      55.3      150    1.90      90 2024-03-10    red       1
4       18.7      22.4      200    1.68      60 2024-07-22   blue       1
5       60.2      45.1       10    1.72      68 2024-02-14  green       0
6       33.8       NaN       50    1.85      85 2024-09-05    red       0
7       41.3      38.7      100    1.78      74 2024-04-18   blue       1
8       29.6      33.4      150    1.65      58 2024-11-30  green       0
9       55.0      60.1      200    1.70      63 2024-08-12    red       1
10      22.4      28.9       10    1.88      82 2024-05-25   blue       0
11      38.1      42.6       50    1.80      78 2024-10-08  green       1
12       NaN       NaN      150    1.62      52 2024-12-01    red       0
13      47.8      52.3      200    1.76      70 2024-03-29   blue       1
14      20.5      24.7       10    1.84      88 2024-09-17  green       0
15      36.2      40.5       50    1.69      62 2024-06-08    red       1
16      52.7      48.9      100    1.73      66 2024-01-22   blue       0
17      44.1       NaN      150    1.87      79 2024-04-05  green       1
18      27.3      32.8      200    1.66      57 2024-10-15    red       0
19      39.6      44.2       10    1.79      76 2024-07-30   blue       1
20      31.4      36.7       50    1.71      65 2024-05-12  green       0
21      48.2      53.9      100    1.83      84 2024-02-28    red       1
22      23.8      27.6      150    1.64      54 2024-08-20   blue       0
23      57.3      62.8      200    1.77      73 2024-11-11  green       1
24      34.5      39.1       10    1.86      86 2024-03-03    red       0
25      42.9      47.4       50    1.63      56 2024-12-20   blue       1
26      19.2      23.5      100    1.81      81 2024-09-09  green       0
27      50.6      55.8      150    1.74      69 2024-06-14    red       1
28      37.4      41.3      200    1.67      61 2024-10-28   blue       0
29      26.8      31.0       10    1.89      87 2024-01-07  green       1
30      45.7      50.2       50    1.61      53 2024-04-22    red       0
31       NaN       NaN      100    1.78      75 2024-07-15   blue       1
32      30.2      35.6      150    1.70      64 2024-02-09  green       0
33      53.4      58.1      200    1.85      83 2024-11-03    red       1
34      21.7      26.3       10    1.68      59 2024-08-28   blue       0
35      40.3      45.8       50    1.76      71 2024-05-19  green       1
36      35.9      38.4      100    1.82      80 2024-12-14    red       0
37      28.1      32.5      150    1.65      56 2024-03-17   blue       1
38      46.4      51.7      200    1.73      67 2024-09-25  green       0
39      24.3      29.0       10    1.88      84 2024-10-02    red       1
40      56.8      61.3       50    1.69      62 2024-07-08   blue       0
41      33.7      37.9      100    1.74      70 2024-01-30  green       1
42      43.2      48.5      150    1.80      77 2024-04-12    red       0
43      17.5      21.8      200    1.66      58 2024-06-25   blue       1
44      49.1      54.4       10    1.72      68 2024-08-16  green       0
45      38.8      43.0       50    1.87      85 2024-11-28    red       1

    age  income   x categorical_column        BMI day_of_week  month  year  \
0    25   30000   2                low  21.484375      Monday      1  2024
1    35   50000   3             medium  26.122449    Saturday      6  2024
2    45   70000   4               high  21.736505     Tuesday     12  2024
3    55   90000   5          very_high  24.930748      Sunday      3  2024
4    28   35000   6                low  21.258503      Monday      7  2024
5    32   48000   7             medium  22.985398   Wednesday      2  2024
6    40   62000   8               high  24.835646    Thursday      9  2024
7    38   55000   9          very_high  23.355637    Thursday      4  2024
8    30   41000  10                low  21.303949    Saturday     11  2024
9    42   68000   2             medium  21.799308      Monday      8  2024
10   27   32000   3               high  23.200543    Saturday      5  2024
11   33   51000   4          very_high  24.074074     Tuesday     10  2024
12   29   38000   5                low  19.814053      Sunday     12  2024
13   44   72000   6             medium  22.598140      Friday      3  2024
14   31   45000   7               high  25.992439     Tuesday      9  2024
15   36   58000   8          very_high  21.707923    Saturday      6  2024
16   48   75000   9                low  22.052190      Monday      1  2024
17   26   29000  10             medium  22.591438      Friday      4  2024
18   34   53000   2               high  20.685150     Tuesday     10  2024
19   41   65000   3          very_high  23.719609     Tuesday      7  2024
20   39   59000   4                low  22.229062      Sunday      5  2024
21   46   71000   5             medium  25.082863   Wednesday      2  2024
22   37   56000   6               high  20.077335     Tuesday      8  2024
23   43   69000   7          very_high  23.301095      Monday     11  2024
24   24   27000   8                low  24.858365      Sunday      3  2024
25   35   54000   9             medium  21.077195      Friday     12  2024
26   47   74000  10               high  24.724520      Monday      9  2024
27   50   78000   2          very_high  22.790329      Friday      6  2024
28   22   25000   3                low  21.872423      Monday     10  2024
29   49   76000   4             medium  24.355421      Sunday      1  2024
30   33   49000   5               high  20.446742      Monday      4  2024
31   38   61000   6          very_high  23.671254      Monday      7  2024
32   29   40000   7                low  22.145329      Friday      2  2024
33   45   70000   8             medium  24.251278      Sunday     11  2024
34   31   46000   9               high  20.904195   Wednesday      8  2024
35   37   57000  10          very_high  22.920971      Sunday      5  2024
36   28   34000   2                low  24.151673    Saturday     12  2024
37   52   81000   3             medium  20.569330      Sunday      3  2024
38   23   26000   4               high  22.386314   Wednesday      9  2024
39   40   63000   5          very_high  23.766410   Wednesday     10  2024
40   44   67000   6                low  21.707923      Monday      7  2024
41   36   55000   7             medium  23.120624     Tuesday      1  2024
42   30   42000   8               high  23.765432      Friday      4  2024
43   43   69000   9          very_high  21.048048     Tuesday      6  2024
44   51   79000  10                low  22.985398      Friday      8  2024
45   32   47000   2             medium  24.307244    Thursday     11  2024

    color_encoded
0        0.562500
1        0.533333
2        0.400000
3        0.562500
4        0.533333
5        0.400000
6        0.562500
7        0.533333
8        0.400000
9        0.562500
10       0.533333
11       0.400000
12       0.562500
13       0.533333
14       0.400000
15       0.562500
16       0.533333
17       0.400000
18       0.562500
19       0.533333
20       0.400000
21       0.562500
22       0.533333
23       0.400000
24       0.562500
25       0.533333
26       0.400000
27       0.562500
28       0.533333
29       0.400000
30       0.562500
31       0.533333
32       0.400000
33       0.562500
34       0.533333
35       0.400000
36       0.562500
37       0.533333
38       0.400000
39       0.562500
40       0.533333
41       0.400000
42       0.562500
43       0.533333
44       0.400000
45       0.562500

#### **Interaction Features**

Interaction features are created by combining two or more variables to capture the interactions between them. These features can reveal relationships that are not apparent when considering the variables independently.

**Example:**

Suppose you have `age` and `income` as features. An interaction term could be created by multiplying these two features to capture how income changes with age.

In [104]:

# Creating an interaction feature
df['age_income_interaction'] = df['age'] * df['income']

print(df)

    feature1  feature2  feature  height  weight       date  color  target  \
0       25.5      30.2       10    1.60      55 2024-01-01    red       1
1       32.1       NaN       50    1.75      80 2024-06-15   blue       0
2        NaN       NaN      100    1.82      72 2024-12-31  green       0
3       45.0      55.3      150    1.90      90 2024-03-10    red       1
4       18.7      22.4      200    1.68      60 2024-07-22   blue       1
5       60.2      45.1       10    1.72      68 2024-02-14  green       0
6       33.8       NaN       50    1.85      85 2024-09-05    red       0
7       41.3      38.7      100    1.78      74 2024-04-18   blue       1
8       29.6      33.4      150    1.65      58 2024-11-30  green       0
9       55.0      60.1      200    1.70      63 2024-08-12    red       1
10      22.4      28.9       10    1.88      82 2024-05-25   blue       0
11      38.1      42.6       50    1.80      78 2024-10-08  green       1
12       NaN       NaN      150    1.62      52 2024-12-01    red       0
13      47.8      52.3      200    1.76      70 2024-03-29   blue       1
14      20.5      24.7       10    1.84      88 2024-09-17  green       0
15      36.2      40.5       50    1.69      62 2024-06-08    red       1
16      52.7      48.9      100    1.73      66 2024-01-22   blue       0
17      44.1       NaN      150    1.87      79 2024-04-05  green       1
18      27.3      32.8      200    1.66      57 2024-10-15    red       0
19      39.6      44.2       10    1.79      76 2024-07-30   blue       1
20      31.4      36.7       50    1.71      65 2024-05-12  green       0
21      48.2      53.9      100    1.83      84 2024-02-28    red       1
22      23.8      27.6      150    1.64      54 2024-08-20   blue       0
23      57.3      62.8      200    1.77      73 2024-11-11  green       1
24      34.5      39.1       10    1.86      86 2024-03-03    red       0
25      42.9      47.4       50    1.63      56 2024-12-20   blue       1
26      19.2      23.5      100    1.81      81 2024-09-09  green       0
27      50.6      55.8      150    1.74      69 2024-06-14    red       1
28      37.4      41.3      200    1.67      61 2024-10-28   blue       0
29      26.8      31.0       10    1.89      87 2024-01-07  green       1
30      45.7      50.2       50    1.61      53 2024-04-22    red       0
31       NaN       NaN      100    1.78      75 2024-07-15   blue       1
32      30.2      35.6      150    1.70      64 2024-02-09  green       0
33      53.4      58.1      200    1.85      83 2024-11-03    red       1
34      21.7      26.3       10    1.68      59 2024-08-28   blue       0
35      40.3      45.8       50    1.76      71 2024-05-19  green       1
36      35.9      38.4      100    1.82      80 2024-12-14    red       0
37      28.1      32.5      150    1.65      56 2024-03-17   blue       1
38      46.4      51.7      200    1.73      67 2024-09-25  green       0
39      24.3      29.0       10    1.88      84 2024-10-02    red       1
40      56.8      61.3       50    1.69      62 2024-07-08   blue       0
41      33.7      37.9      100    1.74      70 2024-01-30  green       1
42      43.2      48.5      150    1.80      77 2024-04-12    red       0
43      17.5      21.8      200    1.66      58 2024-06-25   blue       1
44      49.1      54.4       10    1.72      68 2024-08-16  green       0
45      38.8      43.0       50    1.87      85 2024-11-28    red       1

    age  income   x categorical_column        BMI day_of_week  month  year  \
0    25   30000   2                low  21.484375      Monday      1  2024
1    35   50000   3             medium  26.122449    Saturday      6  2024
2    45   70000   4               high  21.736505     Tuesday     12  2024
3    55   90000   5          very_high  24.930748      Sunday      3  2024
4    28   35000   6                low  21.258503      Monday      7  2024
5    32   48000   7             medium  22.985398   Wednesday      2  2024
6    40   62000   8               high  24.835646    Thursday      9  2024
7    38   55000   9          very_high  23.355637    Thursday      4  2024
8    30   41000  10                low  21.303949    Saturday     11  2024
9    42   68000   2             medium  21.799308      Monday      8  2024
10   27   32000   3               high  23.200543    Saturday      5  2024
11   33   51000   4          very_high  24.074074     Tuesday     10  2024
12   29   38000   5                low  19.814053      Sunday     12  2024
13   44   72000   6             medium  22.598140      Friday      3  2024
14   31   45000   7               high  25.992439     Tuesday      9  2024
15   36   58000   8          very_high  21.707923    Saturday      6  2024
16   48   75000   9                low  22.052190      Monday      1  2024
17   26   29000  10             medium  22.591438      Friday      4  2024
18   34   53000   2               high  20.685150     Tuesday     10  2024
19   41   65000   3          very_high  23.719609     Tuesday      7  2024
20   39   59000   4                low  22.229062      Sunday      5  2024
21   46   71000   5             medium  25.082863   Wednesday      2  2024
22   37   56000   6               high  20.077335     Tuesday      8  2024
23   43   69000   7          very_high  23.301095      Monday     11  2024
24   24   27000   8                low  24.858365      Sunday      3  2024
25   35   54000   9             medium  21.077195      Friday     12  2024
26   47   74000  10               high  24.724520      Monday      9  2024
27   50   78000   2          very_high  22.790329      Friday      6  2024
28   22   25000   3                low  21.872423      Monday     10  2024
29   49   76000   4             medium  24.355421      Sunday      1  2024
30   33   49000   5               high  20.446742      Monday      4  2024
31   38   61000   6          very_high  23.671254      Monday      7  2024
32   29   40000   7                low  22.145329      Friday      2  2024
33   45   70000   8             medium  24.251278      Sunday     11  2024
34   31   46000   9               high  20.904195   Wednesday      8  2024
35   37   57000  10          very_high  22.920971      Sunday      5  2024
36   28   34000   2                low  24.151673    Saturday     12  2024
37   52   81000   3             medium  20.569330      Sunday      3  2024
38   23   26000   4               high  22.386314   Wednesday      9  2024
39   40   63000   5          very_high  23.766410   Wednesday     10  2024
40   44   67000   6                low  21.707923      Monday      7  2024
41   36   55000   7             medium  23.120624     Tuesday      1  2024
42   30   42000   8               high  23.765432      Friday      4  2024
43   43   69000   9          very_high  21.048048     Tuesday      6  2024
44   51   79000  10                low  22.985398      Friday      8  2024
45   32   47000   2             medium  24.307244    Thursday     11  2024

    color_encoded  age_income_interaction
0        0.562500                  750000
1        0.533333                 1750000
2        0.400000                 3150000
3        0.562500                 4950000
4        0.533333                  980000
5        0.400000                 1536000
6        0.562500                 2480000
7        0.533333                 2090000
8        0.400000                 1230000
9        0.562500                 2856000
10       0.533333                  864000
11       0.400000                 1683000
12       0.562500                 1102000
13       0.533333                 3168000
14       0.400000                 1395000
15       0.562500                 2088000
16       0.533333                 3600000
17       0.400000                  754000
18       0.562500                 1802000
19       0.533333                 2665000
20       0.400000                 2301000
21       0.562500                 3266000
22       0.533333                 2072000
23       0.400000                 2967000
24       0.562500                  648000
25       0.533333                 1890000
26       0.400000                 3478000
27       0.562500                 3900000
28       0.533333                  550000
29       0.400000                 3724000
30       0.562500                 1617000
31       0.533333                 2318000
32       0.400000                 1160000
33       0.562500                 3150000
34       0.533333                 1426000
35       0.400000                 2109000
36       0.562500                  952000
37       0.533333                 4212000
38       0.400000                  598000
39       0.562500                 2520000
40       0.533333                 2948000
41       0.400000                 1980000
42       0.562500                 1260000
43       0.533333                 2967000
44       0.400000                 4029000
45       0.562500                 1504000

**Polynomial features** are created by generating new features that are polynomial combinations of the existing features. This can be particularly useful when modeling non-linear relationships.

**Example:**

Suppose you have a single feature `x`. You can create polynomial features like `x^2`, `x^3`, etc., which may help in capturing the non-linear relationships in the data.

In [107]:
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd

# Impute missing values in numerical_df before creating polynomial features
numerical_df_imputed = numerical_df.fillna(numerical_df.mean())

# Creating polynomial features (degree 2)
poly = PolynomialFeatures(degree=2, include_bias=False)
poly_features = poly.fit_transform(numerical_df_imputed)

# Convert the polynomial features back to a DataFrame
# The columns names will be based on the numerical_df columns
df_poly = pd.DataFrame(poly_features, columns=poly.get_feature_names_out(numerical_df_imputed.columns))

print(df_poly)

     feature1  feature2  feature  height  weight  target   age   income     x  \
0   25.500000   30.2000     10.0    1.60    55.0     1.0  25.0  30000.0   2.0
1   32.100000   41.3425     50.0    1.75    80.0     0.0  35.0  50000.0   3.0
2   37.374419   41.3425    100.0    1.82    72.0     0.0  45.0  70000.0   4.0
3   45.000000   55.3000    150.0    1.90    90.0     1.0  55.0  90000.0   5.0
4   18.700000   22.4000    200.0    1.68    60.0     1.0  28.0  35000.0   6.0
5   60.200000   45.1000     10.0    1.72    68.0     0.0  32.0  48000.0   7.0
6   33.800000   41.3425     50.0    1.85    85.0     0.0  40.0  62000.0   8.0
7   41.300000   38.7000    100.0    1.78    74.0     1.0  38.0  55000.0   9.0
8   29.600000   33.4000    150.0    1.65    58.0     0.0  30.0  41000.0  10.0
9   55.000000   60.1000    200.0    1.70    63.0     1.0  42.0  68000.0   2.0
10  22.400000   28.9000     10.0    1.88    82.0     0.0  27.0  32000.0   3.0
11  38.100000   42.6000     50.0    1.80    78.0     1.0  33.0  51000.0   4.0
12  37.374419   41.3425    150.0    1.62    52.0     0.0  29.0  38000.0   5.0
13  47.800000   52.3000    200.0    1.76    70.0     1.0  44.0  72000.0   6.0
14  20.500000   24.7000     10.0    1.84    88.0     0.0  31.0  45000.0   7.0
15  36.200000   40.5000     50.0    1.69    62.0     1.0  36.0  58000.0   8.0
16  52.700000   48.9000    100.0    1.73    66.0     0.0  48.0  75000.0   9.0
17  44.100000   41.3425    150.0    1.87    79.0     1.0  26.0  29000.0  10.0
18  27.300000   32.8000    200.0    1.66    57.0     0.0  34.0  53000.0   2.0
19  39.600000   44.2000     10.0    1.79    76.0     1.0  41.0  65000.0   3.0
20  31.400000   36.7000     50.0    1.71    65.0     0.0  39.0  59000.0   4.0
21  48.200000   53.9000    100.0    1.83    84.0     1.0  46.0  71000.0   5.0
22  23.800000   27.6000    150.0    1.64    54.0     0.0  37.0  56000.0   6.0
23  57.300000   62.8000    200.0    1.77    73.0     1.0  43.0  69000.0   7.0
24  34.500000   39.1000     10.0    1.86    86.0     0.0  24.0  27000.0   8.0
25  42.900000   47.4000     50.0    1.63    56.0     1.0  35.0  54000.0   9.0
26  19.200000   23.5000    100.0    1.81    81.0     0.0  47.0  74000.0  10.0
27  50.600000   55.8000    150.0    1.74    69.0     1.0  50.0  78000.0   2.0
28  37.400000   41.3000    200.0    1.67    61.0     0.0  22.0  25000.0   3.0
29  26.800000   31.0000     10.0    1.89    87.0     1.0  49.0  76000.0   4.0
30  45.700000   50.2000     50.0    1.61    53.0     0.0  33.0  49000.0   5.0
31  37.374419   41.3425    100.0    1.78    75.0     1.0  38.0  61000.0   6.0
32  30.200000   35.6000    150.0    1.70    64.0     0.0  29.0  40000.0   7.0
33  53.400000   58.1000    200.0    1.85    83.0     1.0  45.0  70000.0   8.0
34  21.700000   26.3000     10.0    1.68    59.0     0.0  31.0  46000.0   9.0
35  40.300000   45.8000     50.0    1.76    71.0     1.0  37.0  57000.0  10.0
36  35.900000   38.4000    100.0    1.82    80.0     0.0  28.0  34000.0   2.0
37  28.100000   32.5000    150.0    1.65    56.0     1.0  52.0  81000.0   3.0
38  46.400000   51.7000    200.0    1.73    67.0     0.0  23.0  26000.0   4.0
39  24.300000   29.0000     10.0    1.88    84.0     1.0  40.0  63000.0   5.0
40  56.800000   61.3000     50.0    1.69    62.0     0.0  44.0  67000.0   6.0
41  33.700000   37.9000    100.0    1.74    70.0     1.0  36.0  55000.0   7.0
42  43.200000   48.5000    150.0    1.80    77.0     0.0  30.0  42000.0   8.0
43  17.500000   21.8000    200.0    1.66    58.0     1.0  43.0  69000.0   9.0
44  49.100000   54.4000     10.0    1.72    68.0     0.0  51.0  79000.0  10.0
45  38.800000   43.0000     50.0    1.87    85.0     1.0  32.0  47000.0   2.0

     feature1^2  ...  target^2  target age  target income  target x   age^2  \
0    650.250000  ...       1.0        25.0        30000.0       2.0   625.0
1   1030.410000  ...       0.0         0.0            0.0       0.0  1225.0
2   1396.847166  ...       0.0         0.0            0.0       0.0  2025.0
3   2025.000000  ...       1.0        55.0        90000.0       5.0  3025.0
4    349.690000  ...       1.0        28.0        35000.0       6.0   784.0
5   3624.040000  ...       0.0         0.0            0.0       0.0  1024.0
6   1142.440000  ...       0.0         0.0            0.0       0.0  1600.0
7   1705.690000  ...       1.0        38.0        55000.0       9.0  1444.0
8    876.160000  ...       0.0         0.0            0.0       0.0   900.0
9   3025.000000  ...       1.0        42.0        68000.0       2.0  1764.0
10   501.760000  ...       0.0         0.0            0.0       0.0   729.0
11  1451.610000  ...       1.0        33.0        51000.0       4.0  1089.0
12  1396.847166  ...       0.0         0.0            0.0       0.0   841.0
13  2284.840000  ...       1.0        44.0        72000.0       6.0  1936.0
14   420.250000  ...       0.0         0.0            0.0       0.0   961.0
15  1310.440000  ...       1.0        36.0        58000.0       8.0  1296.0
16  2777.290000  ...       0.0         0.0            0.0       0.0  2304.0
17  1944.810000  ...       1.0        26.0        29000.0      10.0   676.0
18   745.290000  ...       0.0         0.0            0.0       0.0  1156.0
19  1568.160000  ...       1.0        41.0        65000.0       3.0  1681.0
20   985.960000  ...       0.0         0.0            0.0       0.0  1521.0
21  2323.240000  ...       1.0        46.0        71000.0       5.0  2116.0
22   566.440000  ...       0.0         0.0            0.0       0.0  1369.0
23  3283.290000  ...       1.0        43.0        69000.0       7.0  1849.0
24  1190.250000  ...       0.0         0.0            0.0       0.0   576.0
25  1840.410000  ...       1.0        35.0        54000.0       9.0  1225.0
26   368.640000  ...       0.0         0.0            0.0       0.0  2209.0
27  2560.360000  ...       1.0        50.0        78000.0       2.0  2500.0
28  1398.760000  ...       0.0         0.0            0.0       0.0   484.0
29   718.240000  ...       1.0        49.0        76000.0       4.0  2401.0
30  2088.490000  ...       0.0         0.0            0.0       0.0  1089.0
31  1396.847166  ...       1.0        38.0        61000.0       6.0  1444.0
32   912.040000  ...       0.0         0.0            0.0       0.0   841.0
33  2851.560000  ...       1.0        45.0        70000.0       8.0  2025.0
34   470.890000  ...       0.0         0.0            0.0       0.0   961.0
35  1624.090000  ...       1.0        37.0        57000.0      10.0  1369.0
36  1288.810000  ...       0.0         0.0            0.0       0.0   784.0
37   789.610000  ...       1.0        52.0        81000.0       3.0  2704.0
38  2152.960000  ...       0.0         0.0            0.0       0.0   529.0
39   590.490000  ...       1.0        40.0        63000.0       5.0  1600.0
40  3226.240000  ...       0.0         0.0            0.0       0.0  1936.0
41  1135.690000  ...       1.0        36.0        55000.0       7.0  1296.0
42  1866.240000  ...       0.0         0.0            0.0       0.0   900.0
43   306.250000  ...       1.0        43.0        69000.0       9.0  1849.0
44  2410.810000  ...       0.0         0.0            0.0       0.0  2601.0
45  1505.440000  ...       1.0        32.0        47000.0       2.0  1024.0

    age income  age x      income^2  income x    x^2
0     750000.0   50.0  9.000000e+08   60000.0    4.0
1    1750000.0  105.0  2.500000e+09  150000.0    9.0
2    3150000.0  180.0  4.900000e+09  280000.0   16.0
3    4950000.0  275.0  8.100000e+09  450000.0   25.0
4     980000.0  168.0  1.225000e+09  210000.0   36.0
5    1536000.0  224.0  2.304000e+09  336000.0   49.0
6    2480000.0  320.0  3.844000e+09  496000.0   64.0
7    2090000.0  342.0  3.025000e+09  495000.0   81.0
8    1230000.0  300.0  1.681000e+09  410000.0  100.0
9    2856000.0   84.0  4.624000e+09  136000.0    4.0
10    864000.0   81.0  1.024000e+09   96000.0    9.0
11   1683000.0  132.0  2.601000e+09  204000.0   16.0
12   1102000.0  145.0  1.444000e+09  190000.0   25.0
13   3168000.0  264.0  5.184000e+09  432000.0   36.0
14   1395000.0  217.0  2.025000e+09  315000.0   49.0
15   2088000.0  288.0  3.364000e+09  464000.0   64.0
16   3600000.0  432.0  5.625000e+09  675000.0   81.0
17    754000.0  260.0  8.410000e+08  290000.0  100.0
18   1802000.0   68.0  2.809000e+09  106000.0    4.0
19   2665000.0  123.0  4.225000e+09  195000.0    9.0
20   2301000.0  156.0  3.481000e+09  236000.0   16.0
21   3266000.0  230.0  5.041000e+09  355000.0   25.0
22   2072000.0  222.0  3.136000e+09  336000.0   36.0
23   2967000.0  301.0  4.761000e+09  483000.0   49.0
24    648000.0  192.0  7.290000e+08  216000.0   64.0
25   1890000.0  315.0  2.916000e+09  486000.0   81.0
26   3478000.0  470.0  5.476000e+09  740000.0  100.0
27   3900000.0  100.0  6.084000e+09  156000.0    4.0
28    550000.0   66.0  6.250000e+08   75000.0    9.0
29   3724000.0  196.0  5.776000e+09  304000.0   16.0
30   1617000.0  165.0  2.401000e+09  245000.0   25.0
31   2318000.0  228.0  3.721000e+09  366000.0   36.0
32   1160000.0  203.0  1.600000e+09  280000.0   49.0
33   3150000.0  360.0  4.900000e+09  560000.0   64.0
34   1426000.0  279.0  2.116000e+09  414000.0   81.0
35   2109000.0  370.0  3.249000e+09  570000.0  100.0
36    952000.0   56.0  1.156000e+09   68000.0    4.0
37   4212000.0  156.0  6.561000e+09  243000.0    9.0
38    598000.0   92.0  6.760000e+08  104000.0   16.0
39   2520000.0  200.0  3.969000e+09  315000.0   25.0
40   2948000.0  264.0  4.489000e+09  402000.0   36.0
41   1980000.0  252.0  3.025000e+09  385000.0   49.0
42   1260000.0  240.0  1.764000e+09  336000.0   64.0
43   2967000.0  387.0  4.761000e+09  621000.0   81.0
44   4029000.0  510.0  6.241000e+09  790000.0  100.0
45   1504000.0   64.0  2.209000e+09   94000.0    4.0

[46 rows x 54 columns]

In this example, the original feature `x` is transformed into two features: `x` and `x^2`, allowing a model to capture quadratic relationships in the data.

---

### Target Encoding with Smoothing
**Target encoding** transforms categorical variables by replacing each category with the mean of the target variable for that category. While this method can capture the relationship between categorical features and the target, it may lead to overfitting, especially when some categories have few observations.

**Smoothing** addresses this issue by balancing the category-specific mean with the overall mean of the target variable. This approach ensures that categories with limited data are not assigned misleadingly extreme values.

#### Smoothing Formula
The smoothed target encoding for a category is calculated as:

$$
\text{Encoding} = \frac{n \cdot \text{Mean}_{\text{category}} + m \cdot \text{Mean}_{\text{global}}}{n + m}
$$

Where:

 - $ n $ is the number of observations for the category.
 - $ \text{Mean}_{\text{category}} $ is the mean target value for the category.
 - $ \text{Mean}_{\text{global}} $ is the overall mean target value across all categories.
 - $ m $ is the smoothing parameter that determines the weight of the global mean.

A higher $ m $ value increases the influence of the global mean, which is particularly useful for categories with few observations.

### Implementation in Python

Here's how you can implement smoothed target encoding using `pandas`

In [108]:
import pandas as pd

def target_encode_smooth(df, cat_col, target_col, m):
    # Compute the global mean
    global_mean = df[target_col].mean()

    # Compute the number of observations and the mean for each category
    agg = df.groupby(cat_col)[target_col].agg(['count', 'mean'])

    # Compute the smoothed means
    smooth = (agg['count'] * agg['mean'] + m * global_mean) / (agg['count'] + m)

    # Map the smoothed means to the original dataframe
    return df[cat_col].map(smooth)

This function calculates the smoothed target encoding for a specified categorical column. You can adjust the smoothing parameter $ m $ based on your dataset's characteristis.

---


More examples with **Feature engineering**.

**a. Creating New Features:**
- **Polynomial Features:** Creating polynomial combinations of existing features to capture non-linear relationships.

In [110]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
df_poly = poly.fit_transform(numerical_df_imputed)


- **Interaction Features:** Combining two or more features to capture interactions.

In [111]:
df['new_feature'] = df['feature1'] * df['feature2']


**b. Encoding Categorical Variables:**
- **One-Hot Encoding:** Converts categorical variables into a series of binary columns.

In [112]:
df_encoded = pd.get_dummies(df, columns=['categorical_column'])

- **Target Encoding:** Replaces categorical values with the mean of the target variable for that category.

In [113]:
df['encoded_column'] = df.groupby('categorical_column')['target'].transform('mean')


**c. Feature Selection:**
- **Correlation Analysis:** Identify features that are highly correlated with the target variable.

In [114]:
# Select only numerical columns for correlation
numerical_df = df.select_dtypes(include=[float, int])

# Calculate the correlation matrix
correlation_matrix = numerical_df.corr()

# Print the correlations with the 'target' variable, sorted in descending order
print(correlation_matrix['target'].sort_values(ascending=False))

target                    1.000000
encoded_column            0.842701
income                    0.348913
age_income_interaction    0.330753
age                       0.323837
height                    0.169898
feature2                  0.161201
weight                    0.144666
color_encoded             0.141165
feature                   0.135649
new_feature               0.132959
feature1                  0.123779
BMI                       0.094750
x                        -0.066391
month                    -0.169946
year                           NaN
Name: target, dtype: float64


Feature engineering is a powerful tool in the data preprocessing process. By creating new features, encoding categorical variables, generating interaction terms, and adding polynomial features, you can significantly enhance the performance of machine learning models. The effectiveness of feature engineering often depends on the domain knowledge and creativity of the practitioner, as it requires understanding the underlying data and the problem being solved.